version: "3.9"
services:
  tenpo-redis:
    container_name: tenpo-redis
    image: redis:8.0-M02-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - tenpo-net
  tenpo-api:
    container_name: tenpo-api
    image: dmunozdp/java-21-t-challenge:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - tenpo-db
    ports:
      - 8080:8080
    networks:
      - tenpo-net
  tenpo-db:
    container_name: tenpo-db
    image: postgres:17.2-alpine3.21
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: journal
    ports:
      - "5432:5432"
    depends_on:
      - tenpo-redis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tenpo-net
networks:
  tenpo-net: 
volumes:
  postgres_data:
  redis_data:

